services:
  frontend:
    build: ./frontend
    ports:
      - 8080:8080
  api:
    image: nginx
    volumes:
      - ./api/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 3000:3000
  products:
    build: ./products
    ports:
      - 3001:3000
  users:
    build: ./users
    ports:
      - 3002:3000
  carts:
    build: ./carts
    ports:
      - 3003:3000
  orders:
    build: ./orders
    ports:
      - 3004:3000
  mysql:
    image: mysql
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mysql_db
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - 3306:80
volumes:
  mysql: