services:
    nginx:
        build: ./nginx
        ports:
            - 8080:80
        volumes:
            - ./pages/:/var/www/html/
    php:
        build: ./php
        volumes:
            - ./pages/:/var/www/html/
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: root
            ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
            ME_CONFIG_BASICAUTH: false
        depends_on:
            - mongo
    mysql:
        image: mysql
        restart: always
        volumes:
            - mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: mysql_db
            MYSQL_ROOT_PASSWORD: root
    phpmyadmin:
        image: phpmyadmin
        environment:
            PMA_HOST: mysql
        ports:
        - 3306:80
volumes:
    mysql: